name: build & run tests (Win)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Setup env
      run: |
        pip install hererocks
        hererocks lua-pkg --lua 5.1 -rlatest --target vs_32
        cmd ${{github.workspace}}\lua-pkg\bin\activate

    - name: Configure CMake & build
      run: |
        cmake -A Win32 -B ${{github.workspace}}\build -DLUA_INCLUDE_DIR="${{github.workspace}}/lua-pkg/include" -DLUA_LIBRARY="${{github.workspace}}/lua-pkg/lib/lua*.lib"
        cmake --build ${{github.workspace}}/build --config Release

    - name: Test
      working-directory: ${{github.workspace}}/build
      env:
       STRESS: 1
      run: |
        ${{github.workspace}}/lua-pkg/bin/lua ../tests/lua/run_tests

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lua-5.1-build
        path: ${{ github.workspace }}/build
